version: 1.0.{build}
clone_folder: c:\projects\myproject
shallow_clone: true
clone_depth: 1

environment:
  matrix:
    - PYTHON: "C:\\Python37"

build: off
test_script:
  - "%PYTHON%\\python.exe -m pip install mypy"
  - "%PYTHON%\\python.exe -m mypy -p bdemeta -m tests.cmake_parser"
  - "%PYTHON%\\python.exe -m unittest"
deploy: off

